language: cpp

compiler:
- clang
- gcc

before_install:
# Get build dependencies
- sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots #libsdl2
- sudo apt-get -qq update
- sudo apt-get -qq install cmake p7zip-full build-essential libsdl2-dev libsdl2-mixer-dev sshpass
# Get SDL
#- wget http://www.libsdl.org/release/SDL-devel-1.2.15-mingw32.tar.gz
#- tar xfz SDL-devel-1.2.15-mingw32.tar.gz
#- sudo cp SDL-1.2.15/bin/* /usr/i586-mingw32msvc/bin/
#- sudo cp -r SDL-1.2.15/include/SDL/* /usr/i586-mingw32msvc/include/
#- sudo cp SDL-1.2.15/lib/* /usr/i586-mingw32msvc/lib/
#- sudo chmod +x /usr/i586-mingw32msvc/bin/sdl-config
# Get SDL Mixer
#- wget http://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-devel-1.2.12-VC.zip
#- unzip SDL_mixer-devel-1.2.12-VC.zip
#- sudo cp -r SDL_mixer-1.2.12/include/* /usr/i586-mingw32msvc/include/
#- sudo cp SDL_mixer-1.2.12/lib/x86/* /usr/i586-mingw32msvc/lib/
install:
- cd $TRAVIS_BUILD_DIR
# Create unix makefiles
- cmake -DCMAKE_BUILD_TYPE=Release
before_script:

script:
# Build CaesarIA
- REVISION_NUMBER=`git rev-list HEAD --count`
- make
after_success:
- cd $TRAVIS_BUILD_DIR/../caesaria-test
# Prepare ZIP archive
- ZIPNAME=caesaria-0.4-$TRAVIS_BRANCH-$REVISION_NUMBER.zip
- "Compress to ${ZIPNAME}"
- zip -r $ZIPNAME *
- chmod 666 $ZIPNAME
# Upload to server
- sshpass -p "$SCP_PASS" scp -v $ZIPNAME dalerank@frs.sourceforge.net:/home/frs/project/opencaesar3/bin/
env:
