language: cpp
compiler:
- gcc
before_install:
# Get build dependencies
- sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots #libsdl2
- sudo apt-get -qq update
- sudo apt-get -qq install cmake p7zip-full build-essential libsdl2-dev libsdl2-mixer-dev sshpass wget
install:
- cd $TRAVIS_BUILD_DIR
# Create unix makefiles
- cmake -DCMAKE_BUILD_TYPE=Release .
before_script:
# Don't ask for confirmation when using scp
- echo -e "Host frs.sourceforge.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- wget --quiet --continue https://www.dropbox.com/s/fw4mrhzo733xtdm/caesaria_latest_resources.zip
- mkdir $TRAVIS_BUILD_DIR/../caesaria-test
- unzip -n caesaria_latest_resources.zip -d $TRAVIS_BUILD_DIR/../caesaria-test
script:
- cd $TRAVIS_BUILD_DIR
- make -j4
after_success:
- cd $TRAVIS_BUILD_DIR/../caesaria-test
# Prepare ZIP archive
- ZIPNAME=caesaria-0.4-linux64-$TRAVIS_BRANCH-`date +"%Y%m%d"`.zip
- echo Compress to $ZIPNAME
- zip -r $ZIPNAME *
- chmod 666 $ZIPNAME
# Upload to server
- sshpass -p "$SCP_PASS" scp -v $ZIPNAME dalerank@frs.sourceforge.net:/home/frs/project/opencaesar3/bin/
- sshpass -p "$SCP_PASS" scp -v *.linux dalerank@frs.sourceforge.net:/home/frs/project/opencaesar3/stuff/
env:
